# Generated by Django 4.2.2 on 2023-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_balance', models.IntegerField(default=0.0)),
                ('account_address', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_pin', models.IntegerField()),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('time_opened', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_opened'],
            },
        ),
        migrations.CreateModel(
            name='Account_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_account_name', models.CharField(max_length=60)),
                ('transaction_type', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=60, null=True)),
                ('balance_before_transaction', models.IntegerField()),
                ('balance_after_transaction', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
