# Generated by Django 4.2.2 on 2023-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
