# Generated by Django 4.2.2 on 2023-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_phone',
            field=models.CharField(max_length=14),
        ),
    ]
