# Generated by Django 4.2.2 on 2023-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_account_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_history',
            name='reason',
        ),
        migrations.AddField(
            model_name='account_history',
            name='amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
