# Generated by Django 4.2.2 on 2023-07-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_history_reason_account_history_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_history',
            name='account_history_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_owner', to='account.account'),
        ),
    ]
