# Generated by Django 4.2.2 on 2023-07-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_account_history_sender_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_history',
            name='sender_name',
            field=models.CharField(max_length=60),
        ),
    ]
