# Generated by Django 4.2.2 on 2023-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_history_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
