# Generated by Django 4.2.2 on 2023-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_account_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_pin',
            field=models.CharField(max_length=6),
        ),
    ]
