# Generated by Django 4.2.2 on 2023-07-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_account_transaction_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_history',
            old_name='receiver_account_name',
            new_name='reciever_account_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
